{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(foo_gauge)" }
   ]
  },
  {
   "title": "Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(foo_counter)" }
   ]
  },
  {
   "title": "Histgram",
   "type": "graph",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "avg(foo_histgram) by (api)" }
   ]
  }
 ]
}